name: Publish project to Maven repository

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up JDK
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: s4u/maven-settings-action@v2.6.0
        name: Generate maven settings
        with:
          servers: |
            [{
              "id": "merchantpug",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]
      - name: Publish with Gradle
        run: ./gradlew build publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }} # password